version: "3.8"

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    command: -js

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
