name = ""
type = "javascript"
account_id = ""
workers_dev = true
compatibility_date = "2022-01-01"

kv_namespaces = [ 
  { binding = "APPS_KV", id = "852c402ebe554a0298149c2dbbba3381" }
]

[build]
command = "npm run build"
[build.upload]
format = "modules"
main = "./worker.mjs"

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "Room" },
  { name = "LOBBY", class_name = "Lobby" }
]

[miniflare]
env_path = ".env"